### ISSUE TITLE
Configurable / re-orderable units

### ISSUE THREAD

**Issue by jm3** [WoLpH/alfred-converter#10]
As a general purpose unit converter, it's hard to anticipate everyone's preferences, accounting for different locales and use cases. Personally, when I enter "**km**" as a base unit, the most likely target unit I'm converting to is **miles** (not microns or femtomets, whatever those are :). Yet I recognize that others might have wildly different preferences; femtomets could be critical for someone else.

So what if the units table lived in a user-editable `JSON` file? I could see 2 benefits from this:

1. user-supported arbitrary units
2. user-customized ordering of units

In general, I'm against over-configurability since it confuses users, but in this case I think it would be OK because users can just stick with the default units and ordering, while tinkerers can customize if they desire. What do others think?

**Comment by WoLpH** [comment]
While it's a bit obscure, you can actually decide the order for yourself. The order is decided by Alfred and it will auto learn from your previous choices. So if you select km to mile often, that will come out as the top result
