### ISSUE TITLE
US fluid ounces as source

### ISSUE THREAD

**Issue by matthaedo** [WoLpH/alfred-converter#11]
When converting from in^3 or other units of volume, I see US fluid ounces as an destination unit option. However, I am unable to input US fluid ounces as a source unit.

**Comment by WoLpH** [comment]
It depends on which one you want, the English or the US version. The list of units can be found here: https://github.com/WoLpH/alfred-converter/blob/master/poscUnits22.xml

Which gives the following options:
- fl osUK
- fl ozUS
- flozUS
- flozUK

Aliases can be added fairly easy by adding them to the constants.py file at the ANNOTATION_REPLACEMENTS
https://github.com/WoLpH/alfred-converter/blob/master/converter/constants.py

**Comment by matthaedo** [comment]
Perfect, thanks!

**Comment by matthaedo** [comment]
I am unable to get "fl ozUS" to work. Perhaps I'm missing something obvious.
<img width="714" alt="floz" src="https://user-images.githubusercontent.com/6862636/35253277-8438e364-ffb2-11e7-980c-8bbdf0434d43.png">

**Comment by WoLpH** [comment]
You're right, somehow the space appears to be messing with the parsing. The `flozUS` works (just tested over here).

I'll create a new bug for that, something similar happens for all units with spaces (i.e. square feet)

**Comment by matthaedo** [comment]
I should have thought to try flozUS. Thank you.

**Comment by WoLpH** [comment]
Maybe, but "fluid ounce" and fl oz" and all variations should work as
well. This is indeed a bug :)

**Comment by WoLpH** [comment]
I've fixed it on dev, should be released soon
