### ISSUE TITLE
Light icons on dark themes?

### ISSUE THREAD

**Issue by emroch** [WoLpH/alfred-converter#13]
I'm not sure if this is even possible, but it would be nice if you could figure out what kind of theme is applied to the Alfred window and adjust the icons based on that.  For instance, any background darker than 70% grey would use a white icon, while everything else uses black.

If this isn't possible, could there be a toggle in the workflow that adjusts the icon color?

**Comment by WoLpH** [comment]
It looks like it is possible using the `alfred_theme_background`: https://www.alfredapp.com/help/workflows/script-environment-variables/

Now the question when I'll have some time to arrange this... unfortunately I can't give any timeframe on that yet. I'll have to add/find a new set of icons and find out where/how to change the code to detect this.

**Comment by WoLpH** [comment]
The images are definitely royalty free, I think I got them here: https://www.shareicon.net/pack/ios7-set-lined-1

It might have been a different site though, I remember browsing a site where I could specify license

**Comment by WoLpH** [comment]
This was recently fixed thanks to @liuzikai

 https://github.com/WoLpH/alfred-converter/pull/17
