### ISSUE TITLE
MPH and FPS not recognized as units

### ISSUE THREAD

**Issue by emroch** [WoLpH/alfred-converter#14]
Miles per hour and feet per second must be spelled out as "miles/hour" or "mi/h".  This is normal for metric folks - kilometers per hour is usually km/h - but imperial speeds are usually specified as mph.  Feet per second is probably less common, but as long as we're changing mph, we might as well throw in fps too.

**Comment by WoLpH** [comment]
I have to say that I'm a bit in doubt about the fps because it's more commonly used for frames per second, but I suppose it will work for now :)

I've updated the code to include these
