### ISSUE TITLE
Simplifying results

### ISSUE THREAD

**Issue by leonardoholberg** [WoLpH/alfred-converter#16]
Hi,
I love your workflow, and use it daily.
However as I have multiple workflows that activate, when I type a number, it gets a bit messy. So would it be possible to remove the binary, octal and hexadecimal number features and dropdown?

Thank you!

**Comment by WoLpH** [comment]
The documentation is lacking a tad but that's already possible.

If you open the Alfred Preferences, go to Workflows and find the `Unit converter`. You can click on the `Configure workflow and variables` button (the `[x]`):
![image](https://user-images.githubusercontent.com/270571/60506699-b4a9df00-9cc6-11e9-8bd8-6038776af482.png)

After that you can disable the specific conversions like this:
![image](https://user-images.githubusercontent.com/270571/60506744-d0ad8080-9cc6-11e9-9dfd-b57d7fb246d8.png)

If they're set to false, they're disabled. Where base 16 is hex, 8 is oct and 2 is binary.
