### ISSUE TITLE
metric/imperial conversions

### ISSUE THREAD

**Issue by klokie** [WoLpH/alfred-converter#19]
hi, great work!
It would be really useful to be able to convert between the following metric & imperial units:

- cups/c
- gallons/gal
- grams/g
- kilograms/kg
- liters/L
- milliliters/ml
- ounces/oz
- pints/pt
- pounds/lbs
- quarts/qt
- tablespoons/tbsp
- teaspoons/tsp

Is this something you can point me toward how to add?
thanks!

**Comment by WoLpH** [comment]
The problem with the imperial units is that even within the imperial system there are variations.

The gallon for example exists as both `galUK` and `galUS`
![image](https://user-images.githubusercontent.com/270571/69740577-e621bc00-1139-11ea-8869-def794f88005.png)

The only ones in this list that are completely unsupported right now are the cups/tablespoons/teaspoons. I guess those were not important to the people that made the units file: http://w3.energistics.org/uom/poscUnits22.xml

Custom units can be added here but require a tiny bit of work: https://github.com/WoLpH/alfred-converter/blob/master/converter/extra_units.py

I'll see if I can get the spoons and cups as extra units of volume.

**Comment by WoLpH** [comment]
The cups are a bit of an issue: https://en.wikibooks.org/wiki/Cookbook:Cup

Metric cup: 250 mL
US cup: 237, 240 or 250 mL
Japanese cup: 180 mL
Indian teacup: 190 mL

I've opted for a simple conversion to tablespoons (tablespoon is 15mL, 16*15=240mL)
And the teaspoon is 5 mL so the tablespoon is exactly 3 teaspoons

**Comment by klokie** [comment]
Outstanding! Thanks!
