### ISSUE TITLE
Rank default unit conversions better 

### ISSUE THREAD

**Issue by sn0wyfall** [WoLpH/alfred-converter#22]
I love this applet, but I think it would greatly benefit from better ranking of unit conversions.

Let's say I want to convert 80°F to °C, which is common. Check out the difference between spotlight and the applet: 

<img width="792" alt="Screen Shot 2020-08-14 at 11 57 45 AM" src="https://user-images.githubusercontent.com/24374968/90268738-75d0dd00-de25-11ea-86c2-81068a53b3bd.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/24374968/90269360-80d83d00-de26-11ea-8a87-9ffa2e67f6e1.png">

Sure, kelvin is nice to have... but is it really something that's necessary? I'm an engineering student who's grown up around the metric student, and even then I don't ever want to convert into Kelvin unless I'm using it for homework, but then I'd be happy to add in an extra "to K." 

It would just make a lot more sense to rank °C as the first choice, and then kelvin, and then Rankine. Same goes to a C to F calculation—rank F, then maybe R or K, and then the last one. 

Let's look at another example: I want to convert 16in to something. Of course, I would MOST LIKELY want the convert it to the metric system; moreover, probably meters or centimeters. Otherwise probably to feet & inches, or maybe even to feet only. Here's what I get:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/24374968/90269065-04ddf500-de26-11ea-838e-0257fafd619f.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/24374968/90269034-fb548d00-de25-11ea-868d-cafb455a35a3.png">

Similarly here, I can't fathom why the conversion for "femtometer" would be ranked higher than feet if you're converting from inches. I hardly believe that anyone uses Alfred for converting inches to femtometers! And also, there's an inch to inch, which doesn't make that much sense to me. 

That being said, I think it's a wonderful tool. I just don't like that I always have to keep digging for the conversion I'm trying to find. Spotlight does the ranking much better in my opinion, but of course I don't use it anymore in favor of Alfred.

I would be happy to give more examples and which items should be ranked higher. I would look into the code but sadly don't know enough about coding to fix it. However, I can do my best to help in some other way.

**Comment by WoLpH** [comment]
The ranking is actually decided by Alfred. That means you can easily influence it by selecting the "correct" result a few times so it learns from your queries

It might help a bit if I only show the top 10 "close" units by default. So 1 kilometer won't show the femtometer conversion. That might help in the searching.

As for inch to inch, that's probably a side effect of the fractional versions of inches (i.e. `2.5"` vs `2 1/2`. That needs to go however, if it's identical it shouldn't be there.

**Comment by sn0wyfall** [comment]
Got it, thanks for the reply! That definitely makes sense. Also makes sense why I keep seeing this, because I never need to select the unit conversions manually. 

That's a good idea about the close conversions. Would it also be possible to turn off some conversions? Maybe that would also help, but it might be difficult to implement.

**Comment by sn0wyfall** [comment]
Also, I apologize if I sound mad or anything! Didn't mean to come off like that.

**Comment by WoLpH** [comment]
No worries, I'm happy to see that people are using it 👍 

I'm definitely going to try and improve the results a bit. It's definitely a bit too messy in some cases, but the drawback of hiding results is that it can be tricky to "guess" the conversion

Disabling of items would be an option as well but I'm not sure what would be the best format. Alfred does offer environment variables as configuration options so that could work. I'll have to think about that for a bit

**Comment by sn0wyfall** [comment]
Thank you! I definitely understand the complications and very much appreciate that you are willing to work with me to resolve this issue. I believe that you have fully understood my issue. There are no more things that you can help me with today. I rate the customer satisfaction 5/5 and would 10/10 rate to a friend. Sincere regards

**Comment by WoLpH** [comment]
I've disabled a bunch of units and added the option to specify a blacklist through the alfred variables.

If you add `kelvin` to that list you won't see it anymore :)
![image](https://user-images.githubusercontent.com/270571/111855905-813e3680-8927-11eb-96c9-b7e815dbb160.png)

Additionally, if the units are too large/small compared to your input it won't show them anymore. So no more femtometers :)

![Uploading image.png…]()

**Comment by sn0wyfall** [comment]
That's excellent! Thanks a lot for the update!
