### ISSUE TITLE
Put units to the right of the number

### ISSUE THREAD

**Issue by sn0wyfall** [WoLpH/alfred-converter#23]
Normally I see units being written to the right of the number, e.g. 5 in or 5 cm. 

However, this doesn't do that. It puts it to the left of the number:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/24374968/90270417-29d36780-de28-11ea-936a-6791f22a96d2.png">

Is it possible to get units to the right side of the number?

**Comment by WoLpH** [comment]
It took a while, but you can configure this now :)

If you go to the workflow variables (this button: 
![image](https://user-images.githubusercontent.com/270571/111853157-0f132500-891a-11eb-8f58-e41f247ec62e.png) ) you can change it.

![image](https://user-images.githubusercontent.com/270571/111853168-19cdba00-891a-11eb-810a-c8119f83ad8e.png)

Either left or right depending on your preference :)

**Comment by sn0wyfall** [comment]
Amazing! Much appreciated!
