### ISSUE TITLE
How should I convert new units

### ISSUE THREAD

**Issue by Dianelynn1** [WoLpH/alfred-converter#27]
Since I need to calculate a lot of PP transfer fee every day, I want to use Alfred to quickly calculate the PP fee result. How can I implement this conversion procedure in your workflow?

The PP fee calculation tool I currently use is shown in the link, and the US dollar is needed. The specific value set is 4.4%+0.3USD
https://www.clothnappytree.com/ppcalculator/
![image](https://user-images.githubusercontent.com/70073278/90963728-d11d6200-e4ec-11ea-806a-42d961917641.png)

Thanks for your help!

**Comment by Dianelynn1** [comment]
I compared your new code formats and put them in this section of the extra_units.py file.

But I still don’t seem to add them correctly, because PP-fee is not available in the Alfred 4

![image](https://user-images.githubusercontent.com/70073278/90995936-fe066d80-e5ef-11ea-89b9-e1a7724d053a.png)

![image](https://user-images.githubusercontent.com/70073278/90996349-19be4380-e5f1-11ea-8760-6252f9229927.png)
Is this because I put the code in the wrong place or is it just that Alfred made a mistake about using the PP hotkey?

Sorry for taking your time again.

**Comment by WoLpH** [comment]
It seems I somehow missed your reply... sorry about that

In any case, it looks like my example was a bit too limited to work. I've tried a little more and I've come up with this code:
```python
    params = dict(
        units=units,
        quantity_types=['money'],
        base_unit='dollar',
    )

    add = 0.3
    fee = 4.4
    multiplier = fee * 0.0105
    convert.Unit(
        id='dollar',
        name='Dollar',
        annotations=['$', 'dollar'],
        conversion_params=('0', '1', '1', '0'),
        **params
    ).register(units)

    convert.Unit(
        id='paypal-fee',
        name='PayPal fee',
        annotations=['pp', 'paypal'],
        conversion_params=('-%s' % add, '1', str(multiplier), '0'),
        **params
    ).register(units)

    convert.Unit(
        id='paypal-total',
        name='PayPal Total',
        annotations=['pt'],
        conversion_params=('-%s' % add, '1', str(1 + multiplier), '0'),
        **params
    ).register(units)
```
If needed you can easily change the 4.4% and +0.3. Note that after editing the code you will have to delete the `units.pickle` file which caches the calculations.

This is how it looks right now:
![image](https://user-images.githubusercontent.com/270571/96322509-a269c680-1019-11eb-9dca-fbb6b6ae1c6f.png)

**Comment by Dianelynn1** [comment]
thank you very much for your help!

This is indeed very practical to me, thanks again!
