### ISSUE TITLE
Subtraction of floating point numbers doesn't work without spaces

### ISSUE THREAD

**Issue by JeffreyCA** [WoLpH/alfred-converter#29]
This doesn't work for example. It gives me a bunch of conversions from inches.
```
100-24.5
100.5-24.5
```

These all work as expected:
```
100- 24.5
100 -24.5
100 - 24.5
24.5-100
100+24.5
100*24.5
100/24.5
```

**Comment by WoLpH** [comment]
Looks like the inch conversion is a bit too trigger happy. I'll put it on my todo list but I can't start on it until apple repairs my laptop so it can take a few weeks :)

**Comment by JeffreyCA** [comment]
Hey, was wondering if you had a chance to look at this issue (assuming your laptop's fixed now 😅) ?

**Comment by WoLpH** [comment]
Yes... I got the laptop back but I've just been busy ;)

I've fixed the bug and it should work without issues again

**Comment by JeffreyCA** [comment]
Awesome, thank you so much! Can confirm it works now.

**Comment by WoLpH** [comment]
I've also added a few other improvements such as blacklists and fixed a bug with split units so you might want to update again.

This will probably be the last update for a little while
