### ISSUE TITLE
Gigabytes and <X>bibytes

### ISSUE THREAD

**Issue by jsumners** [WoLpH/alfred-converter#3]
Thank you for the tool. It's almost solving my needs.

I need to do conversions like "32GB to bytes", but the highest metric I see supported is MB. It's also be nice to support explicit differences between "GB", "Gb", and "GiB" (along with the corresponding other units).

**Comment by WoLpH** [comment]
To be honest, it's been bugging me as well. Right now I don't have any custom units but simply support the units that are in the units file which I downloaded from a standards website. And... they are definitely lacking.

I'm working on fixing this but it will take me a week or two to actually get it done. So stay tuned :)

**Comment by jsumners** [comment]
Sounds great. I look forward to the update.

**Comment by WoLpH** [comment]
Well, took quite a bit more time but I've added full binary and decimal bit and byte support up to petabyte.

So you now have megabit, mebibit, megabyte and mebibyte :)

**Comment by jsumners** [comment]
Thank you very much.
