### ISSUE TITLE
Farad derivatives support?

### ISSUE THREAD

**Issue by QrchackOfficial** [WoLpH/alfred-converter#30]
I see there's already support for base unit, F (farad). Can nF, pF, uF be added, so I don't have to use meters (nm/pm) and translate in my head? It's especially tricky for um, which is shown as microns - having uF would be much appreciated.

**Comment by WoLpH** [comment]
Both microfarad and picofarad are already supported, but they are hidden by default because the difference in conversions is too large. The current version has a default limit of 3 orders of magnitude which hides these conversions since they're all 6 orders of magnitude apart.

I'll see if I can only apply the order of magnitude limitation when we go beyond 10 results or so.

**Comment by QrchackOfficial** [comment]
This is with MAX_MAGNITUDE at 10000000:

![image](https://user-images.githubusercontent.com/3584315/112158417-70701800-8be8-11eb-86be-77adc123c3fa.png)

nF would be useful here

Also seems like it's not picked up at all:

![image](https://user-images.githubusercontent.com/3584315/112158475-7cf47080-8be8-11eb-8af3-9021f9cada06.png)

uF/pF seem to work fine after changing MAX_MAGNITUDE

**Comment by WoLpH** [comment]
We now have more units available:
![image](https://user-images.githubusercontent.com/270571/113506395-ef4c4580-9544-11eb-8c9c-7c45573bf866.png)

**Comment by QrchackOfficial** [comment]
Looks great, can't wait to try it out!

**Comment by QrchackOfficial** [comment]
![image](https://user-images.githubusercontent.com/3584315/113508882-c337c100-9552-11eb-9240-0bc7f1541042.png)
Something still is up, it shows 1 pico = 1 nano, and 1 "picro" (typo?) being duplicate, but correct value. Appreciate the prompt update though, thank you so much for all the effort - just reporting what I see.

**Comment by WoLpH** [comment]
indeed, typos and a copy paste mistake... I wasn't properly awake yet ;)

**Comment by WoLpH** [comment]
The `picrofarad` is broken in the original file I based most of the units on: http://w3.energistics.org/uom/poscUnits22.xml

The mistake with nano is indeed a copy/paste error from me.

Both are fixed now :)

**Comment by QrchackOfficial** [comment]
Looks like it! Thanks!
