### ISSUE TITLE
Some HEX numbers are not recognized

### ISSUE THREAD

**Issue by YCHX** [WoLpH/alfred-converter#32]
Some numbers such as `0x1f`, `0x2f`,`0x2F` that begin with a number followed by `F` will not be recognized as a hex number. Here is the results:  
<img width="664" alt="Xnip-2021-05-21_14-14-58" src="https://user-images.githubusercontent.com/11978267/119085607-04226100-ba3f-11eb-8edd-72f765a52fb7.png">
<img width="664" alt="Xnip-2021-05-21_14-15-06" src="https://user-images.githubusercontent.com/11978267/119085612-0684bb00-ba3f-11eb-8536-72f05577c704.png">
<img width="664" alt="Xnip-2021-05-21_14-15-16" src="https://user-images.githubusercontent.com/11978267/119085615-084e7e80-ba3f-11eb-9ff2-81bcdb836eec.png">

**Comment by WoLpH** [comment]
It looks like the unit converter is a bit too eager indeed. I guess the entire unit conversion should be disabled for non-base-10 numbers. That's going to take a bit of work though :)

**Comment by WoLpH** [comment]
I've fixed it so the base conversion (hex, octal and binary) conversions happen before the unit parsing happens. So this should always work :)
