### ISSUE TITLE
Timezones would be a nice addition

### ISSUE THREAD

**Issue by peterrussell** [WoLpH/alfred-converter#33]
It would be great if I could type a quart such as 10:00BST to EDT or 10:00 London to New York and get the relevant time in the identified timezone.

So, typing:
10:00EDT BST
would give:
BST 15:00 (3:00 PM)

By default you could convert any time with timezone to the local timezone (and maybe UTC also)

So, if I were in the UK, typing:
10:00 EDT 
would give:
BST 15:00 (3:00 PM)
UTC 14:00 (2:00 PM)

or if possible, optionally using city names rather than timezone identifiers:
10:00 New York
would give:
BST 15:00 (3:00 PM)
UTC 14:00 (2:00 PM)

Would be even better if I could configure a selection of "favoured timezones" that I use and also give those

**Comment by WoLpH** [comment]
While I agree that would be a useful addition, I'm wondering if that hasn't been done before :)

I found this one that looks good: https://www.packal.org/workflow/timezones-2
Doesn't that do everything you need already? I don't mind adding it, but reinventing the wheel is a waste of time ;)

**Comment by peterrussell** [comment]
Hi,

That is probably a good idea - I like that yours need no keyword and just seems "smarter". Also - I always like to prefer fewer plugins rather than more.

However, I think you are right - best to focus on a core set of features than tray nd be a "jack of all trades, master of none".

Thanks for the response and thanks for the Alfred plugin, it is the best I have found for this job.

thanks

Pete
