### ISSUE TITLE
Option to change decimal separator

### ISSUE THREAD

**Issue by leonardoholberg** [WoLpH/alfred-converter#34]
It would be great to change the decimal separator from (.) to (,)

**Comment by WoLpH** [comment]
I've been working on it a little... but there are a few snags. The library also supports functions, and these use commas to separate the arguments. For example: `log(100, 10)`

I could just replace the output however

**Comment by WoLpH** [comment]
I've added configurable decimal separators for the **output**.

Because of the `log(100,10)` support I can't properly handle the input without breaking other conversions.

**Comment by WoLpH** [comment]
It can be downloaded here: https://github.com/WoLpH/alfred-converter/blob/master/unit_converter.alfredworkflow

**Comment by leonardoholberg** [comment]
Thank you!
