### ISSUE TITLE
Doesn't work with negative values of temperature

### ISSUE THREAD

**Issue by Korean-David** [WoLpH/alfred-converter#35]
For example, if I type 90f in Alfred, it correctly shows 90 degree Fahrenheit in Kelvin and Celsius. 
But if I type 30f, it doesn't show the result, because it's a negative value in other units.

**Comment by WoLpH** [comment]
What's the issue you're seeing? It is working fine for me.

It should be noted that Kelvin doesn't go negative. 0 Kelvin is the lowest temperature possible.

![image](https://user-images.githubusercontent.com/270571/139768221-f7d39827-34b7-4197-ac39-731cf8809591.png)

![image](https://user-images.githubusercontent.com/270571/139768318-a8ec6d37-264c-4cd1-a940-5a46a685aebb.png)

![image](https://user-images.githubusercontent.com/270571/139768631-85a66349-167a-4e10-9d4f-27b0b3a0bca0.png)

**Comment by Korean-David** [comment]
Thanks for responding my inquiry. This is what I see:
<img width="964" alt="Screen Shot 2021-11-01 at 7 46 06 PM" src="https://user-images.githubusercontent.com/89657008/139769187-7cc2a53d-a1d5-490b-8d81-739f5d4e98c5.png">

My mac is on Monterey 12.0.1.

**Comment by WoLpH** [comment]
Are you sure you're using the latest version?

I did find a different issue with fahrenheit, `0f` would give an issue for me. That's fixed in the new release: https://github.com/WoLpH/alfred-converter/blob/master/unit_converter.alfredworkflow

**Comment by Korean-David** [comment]
> Are you sure you're using the latest version?
> 
> I did find a different issue with fahrenheit, `0f` would give an issue for me. That's fixed in the new release: https://github.com/WoLpH/alfred-converter/blob/master/unit_converter.alfredworkflow

I just downloaded the new version that you mentioned, and now it works! Thanks. This is the best converter workflow I've ever used. I really appreciate it.
