### ISSUE TITLE
1024mb should be equal to 1.000gb

### ISSUE THREAD

**Issue by welcomeacheron** [WoLpH/alfred-converter#36]
Hello, first of all thank you for the conversion tool provided. I found a problem in the process of using the computer unit conversion.

The computer storage unit conversion error, for example, 1024mb should be equal to 1.000gb, and the tool conversion result is equal to 1.024gb, the storage unit conversion should be 1024.

**Comment by WoLpH** [comment]
I think you're confusing megabit with me**bi**bit.
Specifically:
M = mega = 1000
Mi = mebi = 1024

So for that conversion you need to convert 1024 mib (or Mib, both will work) instead of 1000 mb.
https://en.wikipedia.org/wiki/Binary_prefix

**Comment by welcomeacheron** [comment]
Thank you for your help, my problem has been solved.

**Comment by WoLpH** [comment]
Happy to hear it. It's an old but still very confusing thing. Lawsuits have been won over this https://www.crn.com/news/channel-programs/189602434/western-digital-settles-hard-drive-capacity-lawsuit.htm
