### ISSUE TITLE
Python 2 removed in macOS 8.3 beta

### ISSUE THREAD

**Issue by jdloft** [WoLpH/alfred-converter#37]
Workflow fails with
```
Reason: launch path not accessible

/usr/bin/python
```
On latest macOS beta the old python 2 binary has been removed.

**Comment by WoLpH** [comment]
Can I assume that Python 3 is available?

The codebase should be compatible so that would be a quick fix

**Comment by jdloft** [comment]
Yes, Apple's python3 is still available at `/usr/bin/python3`. I imagine this is just a matter of changing the shebangs?

**Comment by jdloft** [comment]
This may be Alfred's bug because it seems to hardcode the interpreter to `/usr/bin/python` in the script filter.

**Comment by jrduncans** [comment]
While Alfred provides instructions for workflows such as this that require Python 2, it seems to imply that workflows _should_ update to Python 3: https://www.alfredapp.com/help/kb/python-2-monterey/

How that is to be done isn't clear, I assume using bash or external script to call `python3` instead.

**Comment by WoLpH** [comment]
I've created a new version that should fix the issue. Can you try? https://github.com/WoLpH/alfred-converter/blob/master/unit_converter.alfredworkflow

**Comment by jrduncans** [comment]
Looks like maybe some hardcoded references to your machine in there? I get this error when I look at debugging mode:

> [17:23:48.325] ERROR: Unit converter[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.6F2116FF-36BE-4F74-936E-6E814709AC47%3E7DD3BDE5-A157-42E5-9376-F681FB50A4E6)] Code 1: Traceback (most recent call last):
  File "converter/main.py", line 102, in <module>
    with open('/Users/rick/workspace/alfred-converter/log.txt', 'a') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rick/workspace/alfred-converter/log.txt'

**Comment by WoLpH** [comment]
Sorry about that. I accidentally left in that debug code

I've uploaded a new version :)
