### ISSUE TITLE
Can you add the 'mil' unit?

### ISSUE THREAD

**Issue by sgoadhouse** [WoLpH/alfred-converter#4]
Can the 'mil' unit be added? 1 mil = 0.001 inch We use it a lot for electronic board dimensions and mechanical dimensions. Yes, I can use inches, but having the decimal place in the right spot helps eliminate confusion when the tool you is in mils.

https://en.wikipedia.org/wiki/Thousandth_of_an_inch

**Comment by WoLpH** [comment]
It's actually already supported :)

Try this: `100 mil` :)

**Comment by sgoadhouse** [comment]
Yea, I missed it the first time somehow and found it later. I should have closed the “issue”. Sorry for missing it.

--
Stephen Goadhouse
Electronics Engineer

University of Virginia
Physics Department
office: room 265
434-982-5594
sgoadhouse@virginia.edu<mailto:sgoadhouse@virginia.edu>
http://faculty.virginia.edu/phys-electronics<http://faculty.virginia.edu/phys-electronics/>

For any Electronics Shop requests, please email the team at phys-electronics@Virginia.EDU<mailto:physics-electronics-shop@Virginia.EDU>
or come see Larry during our Electronics Shop Walk-In hours:
Tues. 11a - 2p and Thurs. 11a - 2p in Physics Rm 115

On Oct 13, 2015, at 11:35 PM, Rick van Hattem <notifications@github.com<mailto:notifications@github.com>> wrote:


It's actually already supported :)

Try this: 100 mil :)
