### ISSUE TITLE
main function references nonexistent location for logfile

### ISSUE THREAD

**Issue by benjamineskola** [WoLpH/alfred-converter#40]
[`converter/main.py l102`](https://github.com/WoLpH/alfred-converter/blob/7104551e562fc177ed48696b39f872b96c0d2ee6/converter/main.py#L102) references `/Users/rick/…`, which will break for anyone whose username is not `rick` (and who doesn't have a directory `~/workspace/alfred-converter`, etc.).

Suggest firstly using `os.environ["HOME"]`, and secondly making the logging path configurable and optional.

**Comment by WoLpH** [comment]
Sorry about that. I accidentally left in that debug code
