### ISSUE TITLE
`/usr/bin/python` is not a thing on the recent mac versions

### ISSUE THREAD

**Issue by akashagarwal7** [wolph/alfred-converter#48]
Any chance we can perhaps use `/usr/bin/env python` instead to let users like myself rely on Anaconda, or perhaps `/usr/bin/python3`?

**Comment by wolph** [comment]
Those scripts are just for testing however. It doesn't make a difference for Alfred as far as I know :)

**Comment by wolph** [comment]
The actual workflow uses `/usr/bin/python3` right now (because Alfred offers those):
![image](https://user-images.githubusercontent.com/270571/207766621-8b07fa41-5ae3-437f-981b-3ccd8f813e98.png)

I've merged your pull request in any case. Thank you for the help!
