### ISSUE TITLE
Blacklist variable input mismatch

### ISSUE THREAD

**Issue by iaian7** [wolph/alfred-converter#50]
The current unit blacklist doesn't work due to a mismatch in default variable naming.

- Line 280 of convert.py references the variable `os.environ.get('UNITS_BLACKLISTED', '')`
- But the default variable in Alfred is `UNITS_BLACKLIST`
- One of these needs to be changed in order to fix the broken functionality

Easiest fix for users is just to rename the variable in Alfred to match the expected input (add `ED` to the end).

Side note, this is by far my favourite unit conversion workflow! All the others seem to require a specific output definition (slow) or conversion keyword (even slower). So happy to see it's updated and working in Alfred 5.

**Comment by iaian7** [comment]
Depending on the desired verbiage, "Units Blacklist" could be desirable from a user stand point. I've created a pull request to support this. https://github.com/wolph/alfred-converter/pull/51

**Comment by wolph** [comment]
Yeah... that's quite silly indeed. Thank you for the help!

**Comment by wolph** [comment]
I've created a new vesion and I've converted all environment variables to Alfred Configuration options now :)

<img width="478" alt="image" src="https://user-images.githubusercontent.com/270571/209442215-ed1e0c9c-9228-4f0a-a697-03bf325e852b.png">

**Comment by iaian7** [comment]
Even better, awesome!
