### ISSUE TITLE
Environment Variables not working

### ISSUE THREAD

**Issue by kavehv** [wolph/alfred-converter#52]
Testing this plugin on macOS Ventura with Alfred 5.0.6, it seems like the options settable via environment variables are not working.  As such, I can't enable BASE_2 or BASE_16.

**Comment by wolph** [comment]
@kavehv You are right... there was a bug in the latest version. I've fixed the issue and created a new release: https://github.com/WoLpH/alfred-converter/blob/master/unit_converter.alfredworkflow

**Comment by wolph** [comment]
@juanfal I think you might have an older version somehow, the `/usr/bin/python` path hasn't been used in some time. Can you try downloading the latest version?

https://github.com/WoLpH/alfred-converter/blob/master/unit_converter.alfredworkflow

**Comment by kavehv** [comment]
Awesome, thank you!  This appears to be working.  I had manually forced the values I wanted before just to get by 🙂
