### ISSUE TITLE
can't get it to start

### ISSUE THREAD

**Issue by pauliusmui** [wolph/alfred-converter#56]
I am a total beginner and installed the workflow but can't find a way to initiate it. Any advice?

**Comment by wolph** [comment]
It's likely that you don't have Python installed. To install it I suggest following this guide: https://docs.python-guide.org/starting/install3/osx/#doing-it-right

Essentially it comes down to 2 commands (and a bit of waiting).
First you need to install Homebrew:
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
Second you need to install Python:
```
brew install python
```

After that it should work :)
