### ISSUE TITLE
Option to display only certain bases

### ISSUE THREAD

**Issue by xxyxxyxyx1** [WoLpH/alfred-converter#8]
I have enjoyed your workflow, but I find the automatic display of answers in non-decimal bases to be distracting, as I will never use them. Is there a simple way to disable this feature, and only display a single answer?

Thank you

**Comment by WoLpH** [comment]
I've created a new release which supports enabling/disabling bases using the environment variables.

After you download the new version (https://github.com/WoLpH/alfred-converter/blob/master/unit_converter.alfredworkflow) you can disable the bases from Alfred:
![image](https://cloud.githubusercontent.com/assets/270571/25417640/cf76c5b4-2a45-11e7-9413-02158393cb7e.png)
